Update README.md to include authentication with Jira Cloud
rybak/jira-gource pull request #3
Opened 2019-05-28 00:50 UTC by Eddie-Hartman

Added Jira Cloud authentication steps to README.

2019-05-28 00:50 UTC, Eddie-Hartman commented
#3 Resolves

2019-05-28 09:05 UTC, rybak commented
Thank you for you contribution!

2019-05-28 09:10 UTC, rybak requested changes

2019-05-28 09:10 UTC, rybak commented on README.md
> +- You will receive a 401 code if you try to just authenticate with a password. You can easily use an API token instead.
Please wrap the text at 80 characters to make it more readable in raw format and in terminals.

2019-05-28 09:10 UTC, rybak commented on README.md
> +- Reference to the removal can be found here: [https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/](https://developer.atlassian.com/cloud/jira/pla
Let's reword this bit and just put description as link text. Maybe something like "You can read about deprecation of basic authentication in Atlassian blog post".

2019-05-28 09:16 UTC, rybak commented
> #3 Resolves

You probably meant `Resolves #2`*. Let's put it in the commit message, and it would also be a good idea to include a direct link to [ https://github.com/rybak/jira-gource/issues/2](https://github.com/rybak/jira-gource/issues/2), since jira-gource is also hosted on other Git mirrors.

\* Footnote: per [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords) it seems that the number should always follow a keyword.

2019-05-29 01:19 UTC, Eddie-Hartman commented
Thanks for the feedback. I haven't contributed on GitHub in a while.

2019-05-31 15:11 UTC, merged